#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## Kill if already running
killall -9 xfsettingsd picom polybar mpd dunst ksuperkey xfce4-power-manager

## xfce4-settings daemon
xfsettingsd &

## polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

bash /home/jack/.config/bspwm/external_rules.sh
bash /home/jack/.config/openbox/monitor_setup.sh
bash /home/jack/.config/openbox/set_wallpaper.sh

## Launch Polybar
bash ~/.config/openbox-themes/themes/polybar.sh

## Enable power management
xfce4-power-manager &

## Start Compositing Manager
exec picom &

## Notification Daemon
exec dunst &

## Start Music Player Daemon
exec mpd &

## Launch Plank
exec plank &

## Thunar Daemon
exec thunar --daemon &

## Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Set wallpaper to betterlockscreen
betterlockscreen -u /home/jack/Pictures/wallpapers/bg-42.jpg


